### ISSUE TITLE
Map changed to the wrong day

### ISSUE THREAD

**Issue by RAMPAGER101214** [jeanropke/RDR2CollectorsMap#1018]
I was in the middle of collecting when my map just automatically uploaded and changed where everything was. It was on June 12th but moved to June 13th it’s only 5:10 here and I am still able to collect things. Where they were. Is there anyway to go back a day on the map?

**Comment by jeanropke** [comment]
It's midnight UTC/GMT 0, cycles changed.
You still can find some items from yesterday because you are next to them.

And yes, you can change the current day:
Enable this setting: 
![image](https://user-images.githubusercontent.com/6243818/84555287-7dbfb400-acf2-11ea-8dab-ac72db9f2e84.png)

Then this one: 
![image](https://user-images.githubusercontent.com/6243818/84555298-8a440c80-acf2-11ea-8550-bc1c38f72515.png)

And then you can change the day: 
![image](https://user-images.githubusercontent.com/6243818/84555312-99c35580-acf2-11ea-8ebb-29c44334f85b.png)
