### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by whytheseaisboilinghot** [jeanropke/RDR2CollectorsMap#1072]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is? Showing cycle 2 on map but the cards are not showing up, 

Should be cycle 3
I have verified 2 locations

Coordinates can be found by setting the `Show coordinates on clic

**Comment by MichalD96** [comment]
Since Naturalist update some items dont spawn corectly and also spawn in different cycles than should be.
Cycle 2 for the cards is definitely correct - just found 6 - 7 cards from cycle 2
If you have problem to find the item in most cases helps change the session/ sometimes restart the game is needed (very rarely)

**Comment by whytheseaisboilinghot** [comment]
That's crazy cuz I was verifying it with a friend who doesn't even live in the same country but yeah I agree the game is super duper buggy so it's just weird that it was able to be a repeated error in two different locations geographically and not just a bug in my session,
