### ISSUE TITLE
Wrong cycles thread

### ISSUE THREAD

**Issue by MadAlice13** [jeanropke/RDR2CollectorsMap#1135]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`
All the American flowers are wrong today March 30,2021 and I do not understand how to report this. I have been using this map for months without any issues until today.

**Comment by MichalD96** [comment]
Yes, that is a game bug. Flowers should be in cycle 6 but for some reason it is messed up in game today. In one session are in cycle 1 in another in cycle 2 and also i found one cardinal flower from cycle 4. 
So you can go to `Customization` tab in menu click `Enable manual cycle input` and adjust the flowers cycle to your session.
Can't do much more because this values are different for everyone today.

**Comment by Ch4roon** [comment]
Have you thought about the "time change" twice a year? : D -> [|
Most of the items do not currently match. And I noticed that they match after a few hours, roughly at 12 p.m. they are incorrect, but from 7 p.m. at night it 's ok.
The table is good therefore, it is time for the reset which does not correspond rather or something like that.

**Comment by Ch4roon** [comment]
Time change was last Saturday (+1h), the collector map does not have the same time as the server, I just checked this afternoon. But this is only one hour, the collectibles map loot table adjusts to server loot table after 6 or 7 hours, not just one so it's not only that.
In my opinion it looks like something as : the collectibles map does not seem to match the server reset time  + 1h for change time last week.

**Comment by MichalD96** [comment]
It may be problem of time change because the same problem was 2021.01.01 because of the year change. Algorithm that generates cycles in game allowed for repeated cycles. Yesterday was the same situation, cycle for flowers - yesterday and today are the same, what shouldn't be possible. And it always fails on that changes. (sometimes even on month change)
It should fix itself in 2 - 3 days.
Is anyone here checked if today's cycles are correct?

**Comment by Ch4roon** [comment]
i just told you i've checked this afternoon, and the problem starts last week ( 7 day minimum ) 

"the collectibles map loot table adjusts to server loot table after 6 or 7 hours since more than a week"
"the collectibles map does not seem to match the server reset time (maybe changed after an update) + 1h for change time last week."

**Comment by MichalD96** [comment]
Today is everything in place, so i think it fixed itself.

**Comment by Ch4roon** [comment]
You wouldn't have a problem with reading? 

0 - It's not my cache, it affects every player every day for a week.


1 - Table loot reset at midday / 12: 00
2 - Server table loot reset at 7 p.m.
= 7 hours during which the server is not synchronized and every day it is set at the same time: 19 h

Your message saying loots are ok at 4 in the morning ...

Hey man, it's been 4 times since I told you that the loots are ok from 7 p.m. to noon the next day. Obviously they are good at 4 am ... as for everyone ... as for me. 

Resume special for u : Every day since 8 days : from noon to 7 p.m. all tables are not synchronized, and from 7 p.m. to noon the next day they are synchronized.

The problem is that the reset is not at the right time and that the table has shifted every day for 1 week. And every day we have 7 hours of beating during which the tables do not match
not, then they are readjusted at 7 p.m. in the evening every day.

The server reset of the day has just taken place, and the loots no longer correspond until 7 p.m. this evening, like every day for a week.

**Comment by MichalD96** [comment]
And i tell you again that it is not possible. Cycles change is exactly at 00:00 UTC/GMT time. You are the only one with this problem, check if you have correct time and timezone on your device.
