### ISSUE TITLE
Mouse not "captured"

### ISSUE THREAD

**Issue by Chewbee** [jeanropke/RDR2CollectorsMap#1136]
I use the Overwolf version of the collector map
It was working beautifully
Now when I open the collector map the mouse is still active in RDO and not active on the map 
If I want to be able to click on the collector map I have to CTRL+TAB to activate overwolf then the mouse acts on the collector map

I hope this is clear enough 

many thanks

**Comment by MichalD96** [comment]
Many people lately report that issue, but we are not the creators of the overlay, you should report that bug to someone who modified map for the Overwolf. We only have website, and all variants of the map like this overlay or mobile apps are made by someone else.
You can try to contact him on reddit (u/bubleeshaark) because i don't see other contact to him.
