### ISSUE TITLE
Map/Icon Toggles

### ISSUE THREAD

**Issue by dtigue** [jeanropke/RDR2CollectorsMap#1151]
I just started using the map, which is pretty nice btw. But as I was going through marking off the stuff I have already picked up, it refreshed and now a lot of items have been toggle off and it won't allow me to change it.

**Comment by MichalD96** [comment]
This is intended map behavior. Items that are permanently toggled off are random, and does not have specific location on the map.
We did it because people was confused they are able to enable for example coin in menu but nothing shows on the map. 
Another thing is Rockstar steal from you a few items every week, I have no idea why this happens, It is probably a game bug, but a lot of people complained that their map inventory after some time does not match this in game. I also experienced it many times. Due to this game bug i recommend to track your progress mainly in game.
