### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by BlaineBingham** [jeanropke/RDR2CollectorsMap#1201]
Why do the gang hideout locations have the wrong times listed? Also, the time frames are always shown for 12 hours when the gang hideouts are never open that long. I went to some of these during the time frames and there's nothing there.

Also, when I go to a treasure map location there's never anything there.

**Comment by MichalD96** [comment]
Gang hideouts spawn times are from game files, and i am sure they are correct. 
Note that it doesn't work like in GTAO that if you go to gang location it will spawn, you have small chance to spawn it even if is already active. You can increase probability to spawn it if you are alone in the session.
Rockstar will not give treasure map to every player that go to treasure map spawn location, this is also RNG very rare spawn. I advice to not bother going from one map location to another, because you will spend hours and not find anything, just plan your route close to this points every day, and one day it will spawn.
