### ISSUE TITLE
Map not showing correct locations, display shows wrong date

### ISSUE THREAD

**Issue by papatubz2026** [jeanropke/RDR2CollectorsMap#1240]
Hi all,
Love this site, thanks to everyone who takes time to make this wonderful tool. For several days, the map has displayed the incorrect date at the top (today is 3/2/24, displays March 3rd).  I am wondering if others have experienced this issue recently/how to fix it?

I see that the map says if the date is incorrect, the cycles haven't been updated yet,  Is there a way I can manually update the cycle on the map or the game so they sync again?  

I've tried the map on both PC and iPhone and both show same issue. 

I've tried to clear my cache on xbox, and join different sessions as older threads have advised. Map is not showing correct locations for some items but correctly showing for others.

Any advise appreciated. Thank you so much!

**Comment by MichalD96** [comment]
Hey. Map works in UTC/GMT [timezone](https://www.timeanddate.com/worldclock/timezone/utc) (the same as game) and date displayed on top of the menu is UTC/GMT date, not in your local date. 
Cycles changes for everyone in the world exactly at the same time (00:00 UTC/GMT time) and also exactly at this time changes map day. Map has a mechanisms to correct itself. 
The only moment you should be worried that something is wrong with map is when you see this dialog:
![image](https://github.com/jeanropke/RDR2CollectorsMap/assets/53737762/620f2404-c596-46a0-83ee-699275867c59)
First of all, make sure you use this website: https://jeanropke.github.io/RDR2CollectorsMap/
there is many copies of our website that works terribly.
If you don't see dialog about not updated cycles the problem is in your game.
It is very common problem. You can try to change session going to menu -> online -> find new session. If that doesn't work you need to, close the game, turn off the console, unplug console power cable for around 30 seconds. That should clear console cache files.
If you have problem with specific items that requires metal detector or flowers additionally you need to go to RDR2 Home screen, launch the game and when screen turn black, immediately hold (PS: L1 + R1) / (Xbox: RB  + LB) on your controller.
When main menu will be loaded release (PS: L1 + R1) / (Xbox: RB  + LB) buttons.
That will clear some of your game settings, but since over 2 years we haven't found better solution for this issue.
