### ISSUE TITLE
Incorrect item Cycle: day #

### ISSUE THREAD

**Issue by Collectomaniac** [jeanropke/RDR2CollectorsMap#1246]
![Screenshot_20240330-232119_Chrome](https://github.com/jeanropke/RDR2CollectorsMap/assets/165535669/73a3787b-cd53-4245-b0e8-b8c718db6efa)
Dont know wath day cycle it is but we are march 31 lmost five hour after the new cycle the goat hair brush isn't where it shows on the map

**Comment by Not0fthiswor1d** [comment]
Same... Changed Servers multiple times... Reset Cache on PS5... Only able to find the Cards and Alcohol... None of the Diggable items show up at all... No Metal Detector ping, no Bumps in the mud to show where to dig... What is going on?

**Comment by MichalD96** [comment]
@Collectomaniac @Not0fthiswor1d I guess today night was a time change in your country. Game is very buggy in these days.
Map is correct, because cycles are independent from any local time. Map day changes always at 00:00 UTC/GMT time.

Possible fix for PC:
  - Make sure your metal detector is really broken, change session 1 - 2 times and check the same spot.
  - Turn off your game, and Rockstar Games Launcher.
  - Go to this location in Windows file explorer:
    `%UserProfile%\Documents\Rockstar Games\Red Dead Redemption 2\Profiles\<your profile ID>`
    and delete "Player" file.
  - Go to this location in Windows file explorer `%localAppData%\Temp` and delete all files with .dat extension.
  - Launch the game.


Possible fix for consoles:
  - Permanently turn off your console (you can unplug power cable for at least 30 seconds).
  - Turn on your console.
  - Go to RDR2 Home screen, launch the game and when screen turn black immediately hold (PS: L1 + R1) / (Xbox: RB  + LB) on your controller.
  - When main menu will be loaded release (PS: L1 + R1) / (Xbox: RB  + LB) buttons.
  - Readjust again all your game settings.

**Comment by Not0fthiswor1d** [comment]
> @Collectomaniac @Not0fthiswor1d I guess today night was a time change in your country. Game is very buggy in these days. Map is correct, because cycles are independent from any local time. Map day changes always at 00:00 UTC/GMT time.
> 
> Possible fix for PC:
> 
> * Make sure your metal detector is really broken, change session 1 - 2 times and check the same spot.
> * Turn off your game, and Rockstar Games Launcher.
> * Go to this location in Windows file explorer:
>   `%UserProfile%\Documents\Rockstar Games\Red Dead Redemption 2\Profiles\<your profile ID>`
>   and delete "Player" file.
> * Go to this location in Windows file explorer `%localAppData%\Temp` and delete all files with .dat extension.
> * Launch the game.
> 
> Possible fix for consoles:
> 
> * Permanently turn off your console (you can unplug power cable for at least 30 seconds).
> * Turn on your console.
> * Go to RDR2 Home screen, launch the game and when screen turn black immediately hold (PS: L1 + R1) / (Xbox: RB  + LB) on your controller.
> * When main menu will be loaded release (PS: L1 + R1) / (Xbox: RB  + LB) buttons.
> * Readjust again all your game settings.

I already did this from a previous tip that mentioned to to do this.. hasn't fixed it... I cant find any special flowers, none of the fossils are detected. I'm standing on a spot that supposedly has buried treasure.. no metal detector ping.. only cards are working, i went to a place where a hairpin wasn't coming up

**Comment by Not0fthiswor1d** [comment]
> > @Collectomaniac @Not0fthiswor1d I guess today night was a time change in your country. Game is very buggy in these days. Map is correct, because cycles are independent from any local time. Map day changes always at 00:00 UTC/GMT time.
> > Possible fix for PC:
> > 
> > * Make sure your metal detector is really broken, change session 1 - 2 times and check the same spot.
> > * Turn off your game, and Rockstar Games Launcher.
> > * Go to this location in Windows file explorer:
> >   `%UserProfile%\Documents\Rockstar Games\Red Dead Redemption 2\Profiles\<your profile ID>`
> >   and delete "Player" file.
> > * Go to this location in Windows file explorer `%localAppData%\Temp` and delete all files with .dat extension.
> > * Launch the game.
> > 
> > Possible fix for consoles:
> > 
> > * Permanently turn off your console (you can unplug power cable for at least 30 seconds).
> > * Turn on your console.
> > * Go to RDR2 Home screen, launch the game and when screen turn black immediately hold (PS: L1 + R1) / (Xbox: RB  + LB) on your controller.
> > * When main menu will be loaded release (PS: L1 + R1) / (Xbox: RB  + LB) buttons.
> > * Readjust again all your game settings.
> 
> I already did this from a previous tip that mentioned to to do this.. hasn't fixed it... I cant find any special flowers, none of the fossils are detected. I'm standing on a spot that supposedly has buried treasure.. no metal detector ping.. only cards are working, i went to a place where a hairpin wasn't coming up

Edit: Seems to suddenly want to work
