### ISSUE TITLE
add loc Map

### ISSUE THREAD

**Issue by EeNoow** [jeanropke/RDR2CollectorsMap#203]
Hello,Congratulations for your work. it's really a very beautiful map. Would it be possible to add a utility. campfires, bandit dens, 4 fishing areas on the Dakota River and plants
campfires = https://cdn.discordapp.com/attachments/599198432741163029/599228644166205441/image0.jpg
den = https://cdn.discordapp.com/attachments/599198432741163029/599228414548901889/image0.jpg

fishing= https://cdn.discordapp.com/attachments/599198432741163029/601953111644438550/image0.jpg

**Comment by iligalodin** [comment]
This might start cluttering the map even more

**Comment by Rakmarok** [comment]
Keep in mind that this map is specifically for the collector role. Adding other stuff would dilute an already pretty feature rich tool.

**Comment by Jugrnot8** [comment]
That's what I keep thinking. At most make it so you can switch it on and off. You're moving around the map so much collecting you don't really need anything else while you are collecting. 

In the other hand your map is the best and instead of going to multiple maps to find what you need I completely understand how beautiful it would be to have all of it in one place. 

Perhaps add a few to unlock the other stuff?  I intend to donate some money now that heard you switched it to us dollars.

**Comment by jeanropke** [comment]
There is another problem with more markers on map: performance.
If you are on pc, type this code on console (F12) `Cookies.set('ignore-days', 'true');` and reload the page.
To disable it, just change the day on menu.

**Comment by Shaftoe62** [comment]
I agree that those markers would be too much and off the mark for this map. 

However, the markers requested are almost exactly what I compiled in what I call a "Starter Map"

[https://www.reddeadonlineclock.com/resources/RedDeadOnlineV2.pdf](https://www.reddeadonlineclock.com/resources/RedDeadOnlineV2.pdf)

There I also added some (not all) markers for free (special) ammo, valuables and the butcher locations. Everything you need to get started with Red Dead Online.

Would be nice to have a scaleable map for this (rather than a PDF) and more complete but that should be another project I think.

**Comment by jeanropke** [comment]
I'll create a separated for this.
