### ISSUE TITLE
Allow parameters to be passed in the URL

### ISSUE THREAD

**Issue by OlivierGagnon** [jeanropke/RDR2CollectorsMap#363]
Feature request:

Allow users to send a list of items as an argument in the url, for example:

https://jeanropke.github.io/RDR2CollectorsMap/index.html?shown_items=coin_draped_bust_silver_dollar,coin_new_yorke_token,bracelet_infanta_turquoise,necklace_richelieu_amethyst

Suggested options:

shown_items - to show the items on the map (in the order specified if Enable custom route is yes)
hide_collection - to hide an entire collection from the map
custom_route - enable or disable custom route

This would allow us to make efficient shortcuts that automatically setup the map to our liking

**Comment by Shaftoe62** [comment]
If you paste a string like 

draped bust silver dollar;new yorke token;infanta turquoise;richelieu amethyst

in the search box you get close to what you are asking.

**Comment by Megalex42** [comment]
Yep that's true! But the idea would be to have a link that you can just click, and get the route immediately

**Comment by AdamNortonUK** [comment]
There could be one way this implemented, with changing the search or adding a second search container that retains the search items text on a refresh so that when you go to the map again these items are automatically entered again, obviously would also need a clear button to clear the box if you didn’t want this to happen, or option to enable or disable the saving.

**Comment by Senexis** [comment]
Took a while, but it's here. You can achieve this by entering `?search=` and then your search query. It's the best of both worlds!

![image](https://user-images.githubusercontent.com/6360733/73211443-89984880-414c-11ea-91b6-869188c2056d.png)
