### ISSUE TITLE
Map Icons Not Retaining Collected Status Upon Cycle Change Now

### ISSUE THREAD

**Issue by singemfrc** [jeanropke/RDR2CollectorsMap#418]
As of today (Sun Dec 8 GMT) whent the cycle changed from 1 to 2, the map icons did not reflect already collected items, they appeared to be reset. In the menus on the left, the correct items were still appearing checked off, but their flags were all reversed (ie when I clicked on an item showing crossed off in the menu, it reset to "uncollected" in the menu whilst the icon went transparent in the map).
![capture000](https://user-images.githubusercontent.com/55866031/70382125-59ca8280-190b-11ea-8f22-bbdd11ea7018.jpg)

**Comment by jonathonbarton** [comment]
Corollary to this, when I loaded the map today the cycle had changed *and* all my inventory had reset.

**Comment by jeanropke** [comment]
Could you confirm if still happening?

**Comment by jonathonbarton** [comment]
Inventory count seems OK, but some items I'd 'crossed off" because I already had at least one of them are uncrossed off today, while others did not update. c.f. Flowers (which 'stuck') vs Cups (which didn't 'stick')
![image](https://user-images.githubusercontent.com/3887073/70668006-382d0c00-1c27-11ea-9416-d0245623b35f.png)

It would be a great feature-add if we had an option to for a "Balanced Dynamic Route" - where if we mark that we have 1 or more of everything, but 0 of just a few things, it DR to those 4-5 items to get us to 1 of everything. Then it DR's everything we have 1 of until we have 2 of everything, etc. 

Always directing us first to the things we have the fewest of.

**Comment by singemfrc** [comment]
> 
> 
> Could you confirm if still happening?

Yes, still happened today. When the cycle reset, my icons all reset from faded to bright when they should have remained faded, while the menus on the left still reflected the correct quantities.

![capture000](https://user-images.githubusercontent.com/55866031/70673642-0e301580-1c38-11ea-829e-538f2fa5de38.jpg)

**Comment by jeanropke** [comment]
I mess up some if condition. This one 406c76d
