### ISSUE TITLE
Collection items sorting

### ISSUE THREAD

**Issue by q1k** [jeanropke/RDR2CollectorsMap#429]
Currently the items are just there, unsorted in the list, seemingly at random order.
I suggest to have them alphabetically sorted,
for the coins they can be by year, and second layer by value (nickel, dime, quarter, etc..).
For the tarot cards, Page comes before Knight.

**Comment by jeanropke** [comment]
The order is based on the collector satchel (not the player satchel). 
https://i.ytimg.com/vi/SmSDmAQX04I/hqdefault.jpg

**Comment by q1k** [comment]
My satchel isn't alphabetic order, it seems to be random tbh. I think it has to do with the order the items are gathered which is terrible if you ask me.
I'd much rather have the meats as plain, minty, origano, thyme,
the items in the wheel to be first those that were used last/most,
and the collections/collectible items, alphabetically.

Btw, have you experienced this weird bug where no matter where I put my repeater back or shoulder it still ends up in the other slot? This is for missions/matchmaking..

**Comment by jonathonbarton** [comment]
I don't think the order quite the same since the PC Release. 
The navigable Collector Satchel (accessed via Escape -> Progress -> Roles -> Collector Satchel or by picking the collector's satchel from the menu) has this order (and is navigable with Q and E):
American Wild Flowers
Cups
Swords
Wands
Pentacles
Bracelets
Earrings
Necklaces
Rings
Alcohol Bottles
Eggs
Arrowheads
Family Heirlooms
Coins

It'd be nice if we could get the list in that order since that's the easy-peasy page that shows the whole collection in one place.
