### ISSUE TITLE
[Feature: Enable dynamic route does not working] 14 December. Cycle 5. 

### ISSUE THREAD

**Issue by SuperFanz** [jeanropke/RDR2CollectorsMap#471]
When feature called "Enable dynamic route" is set to "Yes", it does not show any routes.

**Comment by maximu** [comment]
It does work with the old cycles, since the new ones are a work in progress we have to make our own route

**Comment by jonathonbarton** [comment]
Since Dynamic Route calculates the "optimal" route based on what you have enabled on the left side (i.e. it removes nodes that you toggle off and recalculates on the fly), I don't see why it wouldn't work, unless it's something relatively simple like needing to update the index of cycles to include numbers higher than 3. 

Theoretically, it *should* dynamically calculate on an arbitrary number of objects on an arbitrary number of cycles, since it does that on the existing cycles. (For instance, you can Dynamically route to ONLY flowers or ONLY the coins you don't yet have...)

**Comment by dlldldl** [comment]
The implementation of dynamic routes are hard coded to each day. By dynamic, it simply removes the item from the chain of hard coded items. It would not be easy to add new ones.
