### ISSUE TITLE
Blood Flower 

### ISSUE THREAD

**Issue by sydthakyd** [jeanropke/RDR2CollectorsMap#562]
Blood Flower not listed (not even in red, knowingly missing) on the day cycle where Wildflowers are dark blue

**Comment by IronJeff80** [comment]
Blood Flower 3, Cycle 1
Blood Flower 5 Cycle 3
Blood Flower 5, Cycle 2
These are all confirmed for Cycle 9 (dark blue)

**Comment by sydthakyd** [comment]
![92C406AB-93AE-431C-BEA4-C71EB6CD75AB](https://user-images.githubusercontent.com/59086914/71264497-3a235900-2312-11ea-88ce-ed30e9f568c7.png)

**Comment by sydthakyd** [comment]
I found two wildflower logos on the map with no name. They just say cycle 9. I’m assuming that’s them, but they still aren’t listed

**Comment by IronJeff80** [comment]
The 2 missing information are Creek Plum (near Big Valley) and Wild Rhubarb (near lake Don Julio). The blood flower is not on the side bar because no items locations were provided at the last update. I have submitted 3 blood flower locations on the discord channel. https://discordapp.com/channels/631510938016677889/655068297284288524 They are also listed above

**Comment by sydthakyd** [comment]
Thank you!

**Comment by becher123** [comment]
i cant find blood flower on the marker i have try in 4 days now i am the only there has this problem

**Comment by kittrellbj** [comment]
> i cant find blood flower on the marker i have try in 4 days now i am the only there has this problem

Make sure you aren't near it when it is time to spawn. If you are near the spawn at 2200 hrs game time, go away and come back.

**Comment by becher123** [comment]
ok i try it thanks

**Comment by becher123** [comment]
yesterday i find blood flower but today i cant find blood flower and iam not near the spawn time is this a game bug
