### ISSUE TITLE
[Volunteering] Roadmap to improve routing

### ISSUE THREAD

**Issue by PakL** [jeanropke/RDR2CollectorsMap#668]
Hey there!

Love the new routing feature and I think it could be improved by creating a roadmap.
For that reason I'd like to volunteer to trace the roads to create a geojson, that would work with [GeoJSON Path Finder](https://github.com/perliedman/geojson-path-finder).

Would that be something you'd be interested in?

**Comment by Senexis** [comment]
While this would definitely be nice, it does raise a performance concern for me.

In its most basic form like it currently is, I would already consider the performance to take at least a minor impact with the current nearest-neighbor process it uses. Using GeoJSON to create "better" paths in by far the most cases, it'll also come with an _additional_ performance penalty on top of what it currently does, because the path finder will have to then go ahead and find a valid path between each of the two points. It could be worth testing it out with a small portion of the map at first, though I suspect it could run into blocking performance on some devices (not everyone uses their main PC to browse the map).

Additionally, this probably won't solve the inconsistencies the current generator has. It'll most likely still skip over some target items if it doesn't think is the nearest neighbor to the source marker. While I could definitely work more towards solving that, it still wouldn't necessarily alleviate the potential performance impact this will have on top of it.

Don't mistake this for a "No, thank you" though! Having the GeoJSON data would definitely be a help towards making the generator better. This is more of a concern regarding the performance impact of the path finder, as it seems to be designed for source-to-target pathing, not a nearest neighbor scenario we currently have.

**Comment by PakL** [comment]
I share your concerns regarding the performance but the [path finder demo](https://www.liedman.net/geojson-path-finder/) doesn't seem too bad; and that thing has 63k nodes which we will probably not even come close to.

Nevertheless I've mapped New Austin in the past 3 hours and will do some tests to check if it's worth investigating further.

**Comment by Senexis** [comment]
Yeah, that's because it's, again, just one path. The problem arises when you scale that to a multitude of items. In our case it's very realistic to have to path 150+ paths for a run. Thanks for doing some of the geojson work already.

**Comment by Senexis** [comment]
I would also like to let you know that those geojson coordinates seem to be off a ways. Inverting the two coordinates still produces an offset map.

**Comment by Senexis** [comment]
I've created a little side track of the page where exporting geojson produces the correct results, and allows me (and you possibly!) to experiment with it. When I import the exported geojson from there, it produces an automatically downloaded file which can be imported correctly without further hassle.

**Comment by Senexis** [comment]
I took some time to map out Lemoyne already. Here it is if you want it: [lemoyne.geojson.txt](https://github.com/jeanropke/RDR2CollectorsMap/files/4027829/lemoyne.geojson.txt).

**Comment by PakL** [comment]
Jup. F*'d it up by using the default earth CRS and not simple. But your data will help me start experimenting with the path finder; thanks!

**Comment by Senexis** [comment]
Let me know how it goes and if it's worth looking at! The beta site'll be up for you to experiment if you want.

**Comment by PakL** [comment]
Oh man. Somehow I thought this was going to be easier than that. I'm not sure it's worth the trouble...

I'm not sure what is happening and how exactly it's working or how the geojson should optimally look like. But right now it's behaving very strangely.

![whatishappening-geojson-path](https://user-images.githubusercontent.com/966377/71925556-9a7b1d00-3191-11ea-9820-862e5186508b.png)

**Comment by Senexis** [comment]
This is most likely because there's different lines, and it can only ever follow one line. The line below the middle marker is different from the other two lines if I recall correctly. The GeoJSON might need to be optimized or otherwise processed before the path finder will work. Is there mention of needing to do anything to it?

**Comment by PakL** [comment]
Alright. The geojson still needs some work. To connect roads properly, two lines must have a (almost) matching coordinate. I've set the precision to 0.04 for now, and that seems to work for the most part.

Here's my progress so far: https://pakl.dev/RDR2CollectorsMap/beta.html
I've piggybacked off of your route generator and am already prefering items with the shortes route. The route is also drawn in realtime.

Currently possible destinations are only limited by the geojson and need further limitations for the future. Probably through the direct distance, like how you've done.

**Comment by PakL** [comment]
I created the rest of the geojson and added a controller to highlight the route to the next item. I'm also presorting the items into chunks to improve performance.

With 211 items it takes a little under a minute on my PC and around 1 min. and 20 sec. on my phone.

To start click 'Generate route' on the Route generator: https://pakl.dev/RDR2CollectorsMap/beta.html

**Comment by q1k** [comment]
Hold on, is this geojson, basically just nodes..?
Can't someone just map out all roads like a web of sorts. Then the pathfinder will follow those..
I'm pretty bad with nodes, so I won't be of much help.

**Comment by Senexis** [comment]
That's what he's doing right now. It has a bunch of "lines" which the pathfinder will follow. It seems progress is being made, but it'll probably need more work. Right now the lines overlap and cause confusion IMO.

**Comment by PakL** [comment]
Currently I'm fixing holes in the road net (e.g. roads not connected properly) and improve performance. I'm already down to ~20 seconds on my PC for 200 items.

After this it'll need a way to cancel route generation.
I'd leave the final implementation to @Senexis.

**Comment by yeradd12** [comment]
So apart of obvious staff like optimization ofc I've collected bunch of items today using your generator and regarding user experience I must say it's very cool. I'd add some improvements like switching current highlighted (sub) route with arrow keys on keyboard but if you are interested in my opinion on that I can only tell I'm looking forward to finally see it in official version of the map.

**Comment by PakL** [comment]
I added keyboard controls fixed the last holes (hopefully) and added optional fast travel routes.

[My pull request is ready.](https://github.com/jeanropke/RDR2CollectorsMap/pull/726)

**Comment by PakL** [comment]
[I added support for Web Worker.](https://github.com/jeanropke/RDR2CollectorsMap/pull/730)

This will improve performance significantly.

**Comment by PakL** [comment]
To get the show on the road [I added options to the menu](https://github.com/jeanropke/RDR2CollectorsMap/pull/741).

That should also conclude this issue. I will continue to work on improvements as I find time for it.

**Comment by NF13** [comment]
@PakL Works nice thanks for the very good work
