### ISSUE TITLE
Map grid (revisited)

### ISSUE THREAD

**Issue by Shaftoe62** [jeanropke/RDR2CollectorsMap#695]
Hi,

Sometime ago I asked you if it would be possible to add a (search) grid to the map.

You will remember this image:
![grid](https://user-images.githubusercontent.com/53898212/72159427-9ed74e00-33bc-11ea-9cc6-4ec1d02ebe1a.jpg)

I guess there is no plugin for Leaflet to do that?

Well, I've come up with another approach to do that;

If it's possible to add another map-tile set (now Default/Detailed/Dark), I could use php and GD Lib to add the grid directly to the map tiles.

That would be quite a complex undertaking so I would like to hear from you in advance if that could work and whether you are interested or not.

I'm imagining something like this:
![grid-design](https://user-images.githubusercontent.com/53898212/72159517-d2b27380-33bc-11ea-8802-86347da0faba.jpg)

**Comment by Senexis** [comment]
Gonna be honest with you, I don't really see how this is useful. The distance bar has some use to give an impression of how much "Distance" as the game calls it an item is apart from another. Not sure how this could benefit the average user, definitely not if it's a lot of effort.

Adding the lines to the map wouldn't be the way since _if_ we were to implement it we would want to give the user the option to hide the lines. Besides, the repo is already over 170MB large partly due to the tiles.

If you can think up a reason you'd want this in the first place I might consider it but I just don't really see any reason other than sharing a position, especially not for a map designed for the collector role to display all items. If anything this'd be something for RDOMap.

**Comment by MichalD96** [comment]
i also don't see the point of that, especially if that mean implement next map version to enough huge project.
but if you find enough good reason to add something like that @Shaftoe62, we can consider to add sticky rulers on top and left, the same as in photoshop
