### ISSUE TITLE
Force reload

### ISSUE THREAD

**Issue by dawn475** [jeanropke/RDR2CollectorsMap#734]
**Is your feature request related to a problem? Please describe.**
I keep trying to reload the map and it will never actually reload on my device till there is about 4-5 hours left before needing to refesh

**Describe the solution you'd like**
A option you can use for when your map wont reload 

**Describe alternatives you've considered**
Closing browser for a while then open and reload. Close out the tab for a bit reloading it not working. Using the refresh button multiple times

**Additional context**
None

**Comment by Senexis** [comment]
What do you mean with "reload" in this case? Do you mean the page doesn't reload or the cycles (colors) don't update to the current day?

**Comment by jalfrezy** [comment]
I have the same issue, after the items in game change locations the map prompts me to refresh the browser because the items have changed. Every time I refresh though nothing happens the items stay where they are and I still get the prompt telling me to refresh my browser this happens for the rest of the day for me.

**Comment by Senexis** [comment]
We made a change 7 days ago that should fix this. Let me know if it still occurs.
