### ISSUE TITLE
Suggestion Fast traven icons

### ISSUE THREAD

**Issue by awaisi88** [jeanropke/RDR2CollectorsMap#79]
Thank you for your efforts

I wish to add Fast Travel location

**Comment by iligalodin** [comment]
if you could give us the lat and long for each location that would be helpful, you can figure that out by enabling show co-ordinates and clicking on the respective locations. Thanks!

**Comment by Rakmarok** [comment]
> if you could give us the lat and long for each location that would be helpful, you can figure that out by enabling show co-ordinates and clicking on the respective locations. Thanks!

Had some time and took it upon myself, as a way of saying thanks for creating this incredibly helpful map (and because I think nobody else wants to bother). I tried to make it as accurate as possible with the hand cursor, using the finger to pinpoint the location.

- **Tumbleweed**: lat: -109.3203125 lng: 26.859375
- **Armadillo**: lat: -104.375 lng: 53.4140625
- **MacFarlane's Ranch**: lat: -101.515625 lng: 72.4140625
- **Manzanita Post**: lat: -88.5859375 lng: 80.7890625
- **Blackwater**: lat: -82.9140625 lng: 99.765625
- **Strawberry**: lat: -70.03125 lng: 84.296875
- **Valentine**: lat: -53.578125 lng: 108.3828125
- **Colter**: lat: -25.9296875 lng: 91.046875
- **Emerald Ranch Station**: lat: -56.7734375 lng: 134.8203125
- **Rhodes**: lat: -83.6640625 lng: 130.65625
- **Wapiti Indian Reservation**: lat: -29.7265625 lng: 118.7890625
- **Van Horn Trading Post**: lat: -53.703125 lng: 156.3203125
- **Annesburg**: lat: -43.46875 lng: 156.765625
- **Saint Denis**: lat: -86.328125 lng: 152.6796875
- **Lagras**: lat: -72.59375 lng: 143.859375

**Comment by iligalodin** [comment]
hey @jeanropke should we add fast travel locations? if so i'll whip out a quick icon for it

**Comment by jeanropke** [comment]
If this icons helps, add them

**Comment by iligalodin** [comment]
#110

**Comment by awaisi88** [comment]
Thank you very much for your interaction
