### ISSUE TITLE
Time is 32 minutes ahead

### ISSUE THREAD

**Issue by CamjacDK** [jeanropke/RDR2CollectorsMap#821]
#### Found a new location? [Use this form here](https://github.com/jeanropke/RDR2CollectorsMap/issues/182)
* What day cycle it is?
* Coordinates or a clear image of the location
* Include the item name

Coordinates can be found by setting the `Show coordinates on click` to `Yes`

**Comment by MichalD96** [comment]
This is not problem with clock on the map. It may be problem with R* server, or cheater in the session. I know the problem because it also happened to me, but time was 11 hours ahead
Since that one situation around a week ago, it never happened again to me
If you change the session time will be correct
