### ISSUE TITLE
Tool Type setting doesn't function properly

### ISSUE THREAD

**Issue by Tiikuri** [jeanropke/RDR2CollectorsMap#861]
Example: if i have metal detector or shovel selected it still shows birds eggs.

Another example if i have metal detector selected as tool type, and have rings visible, it still shows each and every one of the rings.

**Comment by MichalD96** [comment]
it is not a bug
you can't get the item you found with metal detector without a shovel, so it means if you selected metal detector, you must have a shovel, otherwise, metal detector is useless.
From other side, on the map is plenty of spots where you need only shovel to get the item.

Eggs are displayed also correctly because you need varm. rifle or bow to get some of them, it is completely different and not related thing to metal detector and shovel

**Comment by Tiikuri** [comment]
Ah, i see. I should do a feature request.

In the game there's the challenge where you have to find a few items with the metal detector, so it would be nice to have a feature to only display items where you need the metal detector.
