### ISSUE TITLE
Flickering when changing selection

### ISSUE THREAD

**Issue by foxm2k** [jeanropke/RDR2CollectorsMap#886]
This was introduced about 1 week ago. When changing the selection show/un-show type of collectable now ALL the icons on the map flicker one time. That makes it very difficult to track where the the new items appear / dissapear. This flickering was not the case 2 weeks ago, it was introduced shortly. Please change back to old behaviour.

**Comment by Senexis** [comment]
While this will be improved further in the future, which will effectively get rid of the "flash", it will not be changed back.

The reason is performance on mobile devices. The reason it didn't "flash" before is because all the markers loaded in at once, now it loads them more efficiently and makes it so that mobile browsers don't hang anymore. In the future, toggling menu items will only update that one category you toggle, and leave all other markers untouched. :)
