### ISSUE TITLE
Bug: Markers Are Automatically Resetting

### ISSUE THREAD

**Issue by ThatKasper** [jeanropke/RDR2CollectorsMap#960]
Over the past month, my markers have been resetting themselves on about a weekly basis. It's a MAJOR pain to go through all of my collections then have to turn around & do it again within a few days. I'm very diligent about my collections & keeping my map updated so I'd like the option to NEVER auto-reset them if possible.

**Comment by MichalD96** [comment]
it happened because we changed a few things in the code, since today update, markers shouldn't reset anymore.
If you use inventory, go to menu settings section -> "Enable advanced inventory options" and in every category you will have new tab with button "Disable collected" - it will disable all collected items from category on the map
