### ISSUE TITLE
Wrong time, compared to game

### ISSUE THREAD

**Issue by maeeh** [jeanropke/RDR2CollectorsMap#991]
Hi,

this is just to let you know, that the time shown in the maps (yes both) is not the same as in the game.

Please take a look at this picture: https://bit.ly/358e1mv

If you need more information, please let me know.

Greetz

Axel

**Comment by maeeh** [comment]
![Uploading RDO_map_wrong_time.png…]()

**Comment by maeeh** [comment]
Seems I closed the issue accidently ;)

**Comment by MichalD96** [comment]
I know about it, it seems to be problem with R* servers because every time i change the session there is different time. It started after the time changes in some countries, earlier it was mostly cheaters problem but now i cant belive  that in every session is someone who change the time.
2 times i had a situation that time changed from 21:59 to 8:00 what was correct to the time on map (i was waiting for night flowers)
Clock on the map is correct because it is real time UTC speed up 30 times (the same is in GTAV)
For now you need to be lucky to join session with correct time.
